# -*- coding: utf-8 -*-
"""Auto‑Decoder training script for Phase 2.

This script trains the *universal* modulated SIREN described in
``functa_siren.py`` together with a learnable embedding table of latent
vectors ``z`` (the *auto‑decoder* approach of DeepSDF).  The training loop
matches the blueprint in ``functa_plan.txt``:

1. Load the spatial‑oracle dataset generated by ``generate_dataset.py``.
2. Initialise a ``nn.Embedding`` of size ``N`` (number of shapes) and
   dimension ``latent_dim`` (default 256).
3. Initialise the ``ModulatedSIREN`` with the same ``latent_dim``.
4. For each mini‑batch of shapes, pull the corresponding ``z`` vectors,
   evaluate the network on the sampled points, and compute a binary cross
   entropy loss.  An L2 regularisation term ``lambda_z * ||z||^2`` keeps
   the latent space compact.
5. Optimise *both* the SIREN parameters and the embedding table jointly.

The script is deliberately lightweight – it can be invoked directly from
the command line or imported as a module.  It does **not** depend on any
project‑specific training utilities, making it easy to modify or extend.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Tuple
from tqdm.auto import tqdm

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# Local import of the modulated SIREN implementation.
from constrained_fm.src.models.functa_siren import ModulatedSIREN, build_modulated_siren


def load_dataset(pt_path: Path) -> Tuple[torch.Tensor, torch.Tensor]:
    """Load the ``.pt`` file produced by ``generate_dataset.py``.

    The file stores a dict ``{"X": X, "Y": Y, "meta": [...]}`` where
    ``X`` has shape ``(N, M, 2)`` and ``Y`` has shape ``(N, M)`` (uint8).
    ``Y`` is cast to ``float`` for BCE loss.
    """
    data = torch.load(pt_path)
    X = data["X"]  # (N, M, 2)
    Y = data["Y"].float()  # (N, M) – convert to float for BCE
    return X, Y




def train(
    data_path: Path,
    epochs: int = 200,
    batch_size: int = 32,
    lr: float = 1e-4,
    lambda_z: float = 1e-4,
    latent_dim: int = 256,
    hidden_dim: int = 256,
    n_layers: int = 4,
    w0: float = 30.0,
    device: str = "cpu",
    save_dir: Path | None = None,
) -> Tuple[ModulatedSIREN, nn.Embedding]:
    """Run the auto‑decoder training loop.

    Returns the trained ``ModulatedSIREN`` instance and the learned embedding
    table.  If ``save_dir`` is provided, both objects are saved as ``siren.pt``
    and ``embedding.pt`` respectively.
    """
    device = torch.device(device)

    # ---------------------------------------------------------------------
    # 1️⃣ Load dataset
    # ---------------------------------------------------------------------
    X, Y = load_dataset(data_path)
    N, M, _ = X.shape
    # Create persistent indices tensor for shuffling safety.
    indices_tensor = torch.arange(N, dtype=torch.long)
    dataset = TensorDataset(indices_tensor, X, Y)
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=(device.type == "cuda"),
    )

    # ---------------------------------------------------------------------
    # 2️⃣ Model + embedding
    # ---------------------------------------------------------------------
    siren = build_modulated_siren(latent_dim=latent_dim, hidden_dim=hidden_dim, n_layers=n_layers).to(device)
    embed = nn.Embedding(N, latent_dim).to(device)
    # Initialise embedding with a standard normal (helps optimisation).
    nn.init.normal_(embed.weight, mean=0.0, std=0.01)

    # Optimiser over *both* parameter groups.
    optimizer = torch.optim.Adam(list(siren.parameters()) + list(embed.parameters()), lr=lr)
    bce_loss = nn.BCELoss()

    # ---------------------------------------------------------------------
    # 3️⃣ Training loop
    # ---------------------------------------------------------------------
    siren.train()
    embed.train()

    # Import vmap once for efficiency
    from torch.func import vmap

    for epoch in tqdm(range(1, epochs + 1), desc="Training Auto-Decoder"):
        epoch_loss = 0.0
        # Unpack idx, X, Y from the DataLoader (indices are already shuffled correctly)
        for idx_batch, X_batch, Y_batch in loader:
            B = X_batch.shape[0]
            idx_batch = idx_batch.to(device)
            X_batch = X_batch.to(device)
            Y_batch = Y_batch.to(device)

            # Retrieve the corresponding latent vectors using the true shuffled indices
            z_batch = embed(idx_batch)

            # Explicit in_dims to avoid silent broadcasting issues
            preds = vmap(siren, in_dims=(0, 0))(X_batch, z_batch)  # (B, M, 1)
            preds = preds.squeeze(-1)  # (B, M)

            loss = bce_loss(preds, Y_batch) + lambda_z * (z_batch ** 2).mean()
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item() * B

        # Average loss per shape (BCELoss already averages over points)
        avg_loss = epoch_loss / N
        if epoch % 10 == 0 or epoch == 1:
            print(f"Epoch {epoch:04d} – avg BCE+L2 loss: {avg_loss:.6f}")

    # ---------------------------------------------------------------------
    # 4️⃣ Save artefacts (optional)
    # ---------------------------------------------------------------------
    if save_dir is not None:
        save_dir = Path(save_dir)
        save_dir.mkdir(parents=True, exist_ok=True)
        torch.save(siren.state_dict(), save_dir / "siren.pt")
        torch.save(embed.state_dict(), save_dir / "embedding.pt")
        print(f"Model and embedding saved to {save_dir}")

    return siren, embed


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train the Functa auto‑decoder (Phase 2)")
    parser.add_argument(
        "--data_path",
        type=str,
        required=True,
        help="Path to the dataset .pt file generated by generate_dataset.py",
    )
    parser.add_argument("--epochs", type=int, default=200, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=32, help="Mini‑batch size")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate for Adam optimizer")
    parser.add_argument(
        "--lambda_z",
        type=float,
        default=1e-4,
        help="L2 regularisation strength on the latent vectors",
    )
    parser.add_argument(
        "--latent_dim",
        type=int,
        default=256,
        help="Dimensionality of the Functa latent vector",
    )
    parser.add_argument(
        "--hidden_dim",
        type=int,
        default=256,
        help="Hidden dimension of the SIREN",
    )
    parser.add_argument(
        "--n_layers",
        type=int,
        default=4,
        help="Number of sinusoidal hidden layers in the SIREN",
    )
    parser.add_argument(
        "--w0",
        type=float,
        default=30.0,
        help="SIREN frequency scaling factor",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Device for training – e.g. 'cpu' or 'cuda:0'",
    )
    parser.add_argument(
        "--save_dir",
        type=str,
        default=None,
        help="Directory to store the trained model and embedding (optional)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    train(
        data_path=Path(args.data_path),
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        lambda_z=args.lambda_z,
        latent_dim=args.latent_dim,
        hidden_dim=args.hidden_dim,
        n_layers=args.n_layers,
        w0=args.w0,
        device=args.device,
        save_dir=args.save_dir,
    )
