# -*- coding: utf-8 -*-
"""The few-shot budget sweep as a standalone LaTeX table.

One row per shot budget N, one column per metric. The sweep over N exists only on the
100-constraint benchmark; the 1000-constraint run was executed at a single budget, so it is
reported as its own block rather than mixed into rows it is not comparable with.

Pure stdlib, so it runs on the login node without the container.

    python3 -m constrained_fm.scripts.table_few_shot
    python3 -m constrained_fm.scripts.table_few_shot --no-val1k-row
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from constrained_fm.scripts.table_val1k import format_cell

DEFAULT_SUMMARY = "constrained_fm/baselines/few_shot/summary.json"
DEFAULT_VAL1K = "constrained_fm/baselines/val1k/metrics.json"
DEFAULT_TABLE = "constrained_fm/tables/few_shot.tex"

# (metric key, column header, decimals, higher_is_better)
METRICS = (
    ("success_rate", r"Acceptance Rate (\%)", 2, True),
    ("swd", "SWD", 4, False),
    ("mmd", "MMD", 5, False),
    ("kld", "KLD", 4, False),
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Emit the few-shot budget sweep as LaTeX.")
    parser.add_argument("--summary", default=DEFAULT_SUMMARY,
                        help="few-shot sweep summary holding per_n_median")
    parser.add_argument("--val1k", default=DEFAULT_VAL1K,
                        help="merged v1k metrics, for the 1000-constraint row")
    parser.add_argument("--out", default=DEFAULT_TABLE, help="path of the .tex file to write")
    parser.add_argument("--label", default="tab:few-shot")
    parser.add_argument("--no-val1k-row", action="store_true",
                        help="report the budget sweep alone")
    return parser


def sweep_rows(summary: dict) -> tuple[list[int], dict[int, dict[str, float]], int]:
    """Per-budget medians, keyed by N in ascending order."""
    per_n = summary["per_n_median"]
    budgets = sorted(int(n) for n in per_n)
    rows = {n: per_n[str(n)] for n in budgets}
    num_constraints = max(int(rows[n].get("count", 0)) for n in budgets)
    return budgets, rows, num_constraints


def val1k_row(path: Path) -> tuple[int, dict[str, float], int] | None:
    """The 1000-constraint run, or None when it has not been merged yet."""
    if not path.exists():
        return None
    payload = json.loads(path.read_text())
    merged = payload.get("methods", {}).get("fewshot")
    if merged is None:
        return None
    summary = merged["summary"]
    values = {key: float(summary.get(f"{key}_median", float("nan")))
              for key, _, _, _ in METRICS}
    n_points = merged.get("eval", {}).get("n_points")
    return int(n_points), values, int(payload["num_constraints"])


def format_row(label: str, values: dict[str, float], best: dict[str, float]) -> str:
    cells = []
    for key, _, decimals, _ in METRICS:
        value = float(values.get(key, float("nan")))
        target = best.get(key)
        is_best = (target is not None and math.isfinite(value)
                   and math.isclose(value, target))
        cells.append(format_cell(value, decimals, is_best))
    return f"{label} & " + " & ".join(cells) + r" \\"


def build_table(summary: dict, extra, label: str) -> str:
    budgets, rows, num_constraints = sweep_rows(summary)

    # Bolding compares budgets against each other, so only rows on one benchmark take part.
    best: dict[str, float] = {}
    for key, _, _, higher_better in METRICS:
        finite = [float(rows[n][key]) for n in budgets
                  if math.isfinite(float(rows[n].get(key, float("nan"))))]
        if finite:
            best[key] = max(finite) if higher_better else min(finite)

    headers = " & ".join(header for _, header, _, _ in METRICS)
    lines = [
        r"% Generated by constrained_fm.scripts.table_few_shot -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{r" + "r" * len(METRICS) + "}",
        r"\toprule",
        rf"$N$ & {headers} \\",
        r"\midrule",
        rf"\multicolumn{{{len(METRICS) + 1}}}{{l}}{{\emph{{{num_constraints}-polynomial "
        r"benchmark}} \\",
    ]
    lines += [format_row(f"{n}", rows[n], best) for n in budgets]

    if extra is not None:
        n_points, values, extra_constraints = extra
        lines += [
            r"\midrule",
            rf"\multicolumn{{{len(METRICS) + 1}}}{{l}}{{\emph{{{extra_constraints}-polynomial "
            r"validation set}} \\",
            format_row(f"{n_points}", values, {}),
        ]

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Few-shot unconstrained baseline as a function of the number of valid "
        r"training samples $N$. For each constraint, $N$ points satisfying $P(x) \le 0$ are "
        r"rejection-sampled and an unconditional flow matcher is trained from scratch on "
        r"them, so every row represents one independently trained model per constraint. "
        r"Values are medians over the benchmark. Training length is chosen by early stopping "
        r"against 10{,}000 held-out constraint-satisfying points, far more data than the "
        r"model is allowed to train on; this removes training length as a confound but makes "
        r"these numbers an optimistic upper bound on the baseline.}",
        rf"\label{{{label}}}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    path = Path(args.summary)
    if not path.exists():
        raise FileNotFoundError(
            f"{path} missing -- run `python -m constrained_fm.scripts.few_shot_unconstrained "
            f"--plot-only` to assemble the sweep first")
    summary = json.loads(path.read_text())

    extra = None if args.no_val1k_row else val1k_row(Path(args.val1k))

    table = build_table(summary, extra, args.label)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(table)

    print(f"wrote {out}")
    print(table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
