# -*- coding: utf-8 -*-
"""The shared-budget sweep as a LaTeX table: Functa vs fine-tuned few-shot at each N.

One row per budget N. Each metric gets a Functa and a few-shot column, and the better of
the two is bolded. Medians are taken over the constraint subset ``shared_budget_results``
defines, which is identical for every row.

Pure stdlib, so it runs on the login node without the container.

    python3 -m constrained_fm.scripts.table_shared_budget
    python3 -m constrained_fm.scripts.table_shared_budget --min-inside 10
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

from constrained_fm.scripts import shared_budget_results as results
from constrained_fm.scripts.table_few_shot import METRICS
from constrained_fm.scripts.table_val1k import format_cell

DEFAULT_TABLE = "constrained_fm/tables/shared_budget.tex"
SHORT_LABELS = {results.FUNCTA: "Functa", results.FEWSHOT: "FS-FT"}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Emit the shared-budget sweep as LaTeX.")
    parser.add_argument("--metrics", default=results.DEFAULT_METRICS, help="merged sweep")
    parser.add_argument("--min-inside", type=int, default=results.DEFAULT_MIN_INSIDE,
                        help="inside points a constraint needs at the smallest budget")
    parser.add_argument("--out", default=DEFAULT_TABLE)
    parser.add_argument("--label", default="tab:shared-budget")
    return parser


def table_rows(by_method: dict, indices: list[int]) -> dict[int, dict]:
    """N -> {"n_inside": median, method: {metric: median}}."""
    rows = {}
    for n in sorted(by_method[results.FUNCTA]):
        row = {"n_inside": results.median(
            results.column(by_method[results.FUNCTA][n], "n_inside", indices))}
        for method in results.METHODS:
            merged = by_method[method][n]
            row[method] = {key: results.median(results.column(merged, key, indices))
                           for key, _, _, _ in METRICS}
        rows[n] = row
    return rows


def format_row(n: int, row: dict) -> str:
    cells = [str(n), f"{row['n_inside']:.0f}"]
    for key, _, decimals, higher_better in METRICS:
        values = {method: row[method][key] for method in results.METHODS}
        finite = [value for value in values.values() if math.isfinite(value)]
        best = (max(finite) if higher_better else min(finite)) if finite else None
        for method in results.METHODS:
            value = values[method]
            is_best = best is not None and math.isfinite(value) and math.isclose(value, best)
            cells.append(format_cell(value, decimals, is_best))
    return " & ".join(cells) + r" \\"


def build_table(rows: dict[int, dict], label: str, num_eligible: int, num_total: int,
                min_inside: int, run_id: str) -> str:
    pair = len(results.METHODS)
    group_headers = " & ".join(rf"\multicolumn{{{pair}}}{{c}}{{{header}}}"
                               for _, header, _, _ in METRICS)
    rules = " ".join(rf"\cmidrule(lr){{{3 + pair * i}-{2 + pair * (i + 1)}}}"
                     for i in range(len(METRICS)))
    method_headers = " & ".join(SHORT_LABELS[method] for _ in METRICS
                                for method in results.METHODS)
    n_min = min(rows)

    lines = [
        rf"% Generated by constrained_fm.scripts.table_shared_budget from {run_id} -- do not edit by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{rr" + "r" * (pair * len(METRICS)) + "}",
        r"\toprule",
        rf" & & {group_headers} \\",
        rules,
        rf"$N$ & $N_{{\mathrm{{in}}}}$ & {method_headers} \\",
        r"\midrule",
        *[format_row(n, rows[n]) for n in sorted(rows)],
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Functa against the fine-tuned few-shot baseline (FS-FT) when both see the "
        r"same $N$ points. For each constraint, $N$ points are drawn from the unconstrained "
        r"GMM target. Functa labels all of them with $\tanh P(x)$ and extracts its latent "
        r"from them with the frozen SIREN; FS-FT fine-tunes the base unconditional flow "
        r"matcher on the $N_{\mathrm{in}}$ of them that satisfy $P(x) \le 0$ (median shown). "
        r"Smaller budgets are prefixes of larger ones. Values are medians over the "
        rf"{num_eligible} of {num_total} validation constraints with at least {min_inside} "
        rf"inside points at $N{{=}}{n_min}$. The SIREN was meta-trained on uniformly "
        r"distributed query points. FS-FT early-stops against 10{,}000 held-out "
        r"constraint-satisfying points, which makes it an optimistic upper bound.}",
        rf"\label{{{label}}}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    payload = results.load(args.metrics)
    by_method = results.budgets(payload)
    indices = results.eligible(by_method, args.min_inside)
    if not indices:
        raise RuntimeError(f"no constraint has {args.min_inside} inside points at the "
                           f"smallest budget")

    rows = table_rows(by_method, indices)
    run_id = next(iter(by_method[results.FUNCTA].values()))["run_id"]
    table = build_table(rows, args.label, len(indices), int(payload["num_constraints"]),
                        args.min_inside, run_id)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(table)

    print(f"{len(indices)}/{payload['num_constraints']} constraints with >= "
          f"{args.min_inside} inside points at N={min(rows)}")
    print(f"wrote {out}")
    print(table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
