# -*- coding: utf-8 -*-
"""Stage 5 of the v1k pipeline: the main comparison table as standalone LaTeX.

Reads only the merged metrics.json and emits a booktabs table of the median Acceptance Rate,
SWD, MMD and KLD over the 1000-constraint validation set, one column per method, plus the
qualitative rows that say what each method actually costs. Pure stdlib, so it runs on the
login node without the container.

    python3 -m constrained_fm.scripts.table_val1k
    python3 -m constrained_fm.scripts.table_val1k --out constrained_fm/tables/val1k_main.tex
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

DEFAULT_OUTDIR = "constrained_fm/baselines/val1k"
DEFAULT_TABLE = "constrained_fm/tables/val1k_main.tex"

# Column order, and the header each method prints under.
COLUMNS = (
    ("coeff", r"Coefficients \textbf{(ours)}"),
    ("fewshot", "Few-shot"),
    ("functa", r"Functa \textbf{(ours)}"),
    ("eci", "ECI"),
    ("hardflow", "HardFlow"),
)

# (metric key, row label, decimals, higher_is_better)
ROWS = (
    ("success_rate", "Acceptance Rate (\\%)", 2, True),
    ("swd", "SWD", 4, False),
    ("mmd", "MMD", 5, False),
    ("kld", "KLD", 4, False),
)

QUALITATIVE = (
    ("constraint supplied as", {
        "coeff": "coefficients",
        "fewshot": "$N$ valid samples",
        "functa": "512-dim latent",
        "eci": "exact $P(x)$ at sampling",
        "hardflow": "exact $P(x)$ at sampling",
    }),
    ("constraint seen during training", {
        "coeff": "yes", "fewshot": "yes", "functa": "yes",
        "eci": r"\textbf{no}", "hardflow": r"\textbf{no}",
    }),
    ("models trained", {
        "coeff": "1", "fewshot": "one per constraint", "functa": "1",
        "eci": "1", "hardflow": "1",
    }),
    ("unseen constraint without retraining", {
        "coeff": "yes", "fewshot": r"\textbf{no}", "functa": "yes",
        "eci": "yes", "hardflow": "yes",
    }),
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Emit the v1k comparison table as LaTeX.")
    parser.add_argument("--outdir", default=DEFAULT_OUTDIR)
    parser.add_argument("--out", default=DEFAULT_TABLE, help="path of the .tex file to write")
    parser.add_argument("--label", default="tab:val1k-main")
    return parser


def median_of(payload: dict, method: str, metric: str) -> float:
    summary = payload["methods"].get(method, {}).get("summary", {})
    return float(summary.get(f"{metric}_median", float("nan")))


def format_cell(value: float, decimals: int, best: bool) -> str:
    if not math.isfinite(value):
        return "n/a"
    text = f"{value:.{decimals}f}"
    return rf"\textbf{{{text}}}" if best else text


def header_for(payload: dict, method: str, label: str) -> str:
    """The shot budget is part of the few-shot baseline's identity, so it goes in the header."""
    if method != "fewshot":
        return label
    n_points = payload["methods"][method].get("eval", {}).get("n_points")
    return f"{label}, $N{{=}}{n_points}$" if n_points else label


def build_table(payload: dict, label: str) -> str:
    present = [(key, name) for key, name in COLUMNS if key in payload["methods"]]
    if not present:
        raise RuntimeError("metrics.json holds none of the expected methods")

    num = payload["num_constraints"]
    headers = [header_for(payload, key, name) for key, name in present]

    lines = [
        r"% Generated by constrained_fm.scripts.table_val1k -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l" + "r" * len(present) + "}",
        r"\toprule",
        "Metric (median) & " + " & ".join(headers) + r" \\",
        r"\midrule",
    ]

    for metric, row_label, decimals, higher_better in ROWS:
        values = [median_of(payload, key, metric) for key, _ in present]
        finite = [v for v in values if math.isfinite(v)]
        target = (max(finite) if higher_better else min(finite)) if finite else None
        cells = [format_cell(v, decimals, target is not None and math.isfinite(v)
                             and math.isclose(v, target)) for v in values]
        lines.append(f"{row_label} & " + " & ".join(cells) + r" \\")

    lines.append(r"\midrule")
    for row_label, mapping in QUALITATIVE:
        cells = [mapping.get(key, "--") for key, _ in present]
        lines.append(f"{row_label} & " + " & ".join(cells) + r" \\")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        rf"\caption{{Median performance over the {num}-polynomial validation set. "
        r"KLD is undefined for ECI and HardFlow, which alter the state outside the "
        r"probability-flow ODE, so no density of theirs is defined.}",
        rf"\label{{{label}}}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    path = Path(args.outdir) / "metrics.json"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} missing -- run `python3 -m constrained_fm.scripts.merge_val1k` first")
    payload = json.loads(path.read_text())

    table = build_table(payload, args.label)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(table)

    print(f"wrote {out} | {payload['num_constraints']} constraints | "
          f"methods {sorted(payload['methods'])}")
    print(table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
